// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK6_Ib1_goZGJ_ERMTnvL6r_9VQAJAU5I',
    appId: '1:512481699621:web:afece72f58aa16af4a9ccc',
    messagingSenderId: '512481699621',
    projectId: 'chat-app-bbf16',
    authDomain: 'chat-app-bbf16.firebaseapp.com',
    storageBucket: 'chat-app-bbf16.appspot.com',
    measurementId: 'G-PLY93MZF3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9rnuYtwQGOy3IoZym0nWafNS9ZdXQ-So',
    appId: '1:512481699621:android:8dfbb6c583c513d74a9ccc',
    messagingSenderId: '512481699621',
    projectId: 'chat-app-bbf16',
    storageBucket: 'chat-app-bbf16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XQn6sC-vpK0q_emuKI77us1HkYc8O-M',
    appId: '1:512481699621:ios:d38ed5c070305d244a9ccc',
    messagingSenderId: '512481699621',
    projectId: 'chat-app-bbf16',
    storageBucket: 'chat-app-bbf16.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4XQn6sC-vpK0q_emuKI77us1HkYc8O-M',
    appId: '1:512481699621:ios:8a243a30070b6b534a9ccc',
    messagingSenderId: '512481699621',
    projectId: 'chat-app-bbf16',
    storageBucket: 'chat-app-bbf16.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
